# 1st Docker build stage: build the project with Maven
FROM maven:3.6.3-openjdk-17 as builder
WORKDIR /project
COPY . /project/
RUN mvn package -DskipTests -B

# 2nd Docker build stage: copy builder output and configure entry point
FROM openjdk:17-jdk-slim
ENV APP_DIR /application
ENV APP_FILE container-fat.jar

EXPOSE 8888

WORKDIR $APP_DIR
COPY --from=builder /project/target/*-fat.jar $APP_DIR/$APP_FILE

ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]


# found at:
# - https://github.com/vertx-howtos/executable-jar-docker-howto/blob/master/docker-maven/Dockerfile
# - https://github.com/vertx-howtos/executable-jar-docker-howto/blob/master/README.adoc
